name: CD


# trigger on merged pull requests or push to master branch
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
# and: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
on:
  pull_request:
    types: [ closed ]
    branches:
      - master

jobs:
  cd-job:
    if: github.event.pull_request.merged == true
    name: Continuous Deployment
    runs-on: ubuntu-latest

    steps:
      - name: SSH remote and deploy application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "deploy application"

      - name: Notify on failure
        if: failure()
        run: echo "notify error"

      - name: Notify on success
        if: success()
        run: echo "notify success"
