name: ci

on:
  pull_request:
    branches:
      - master
      - release*

env:
  GO_VERSION: 1.18.2

jobs:
  ci:
    needs: build
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Start application in background
        run: |
          echo "start application in background"

      - name: Run smoke test
        run: |
          echo "run smoke test"

      # other test