name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GO_VERSION: 1.18.2

jobs:
  publish-binary:
    name: Publish binary on linux and macos
    strategy:
      matrix:
        os: [ macos-10.15, ubuntu-20.04 ]
    runs-on: ${{matrix.os}}

    steps:
      - name: Set up Go${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Go Build Project
        run: make publish-binary

      - name: Release Binary
        uses: softprops/action-gh-release@v1
        with:
          files: build/**.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docker:
    name: Publish docker images
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build and push docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: repo/project
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tag_names: true